require('settings')
require('packer-config')
require('colorschemes.nightfox')
require('lsp-zero-config')
require('compleation')
require('nvim-tree-config')
require('mappings')
require('lua-line-config')
