-- require('core.plugin_config.tokyonight')
require('core.plugin_config.catppuccin')
require('core.plugin_config.neodev')
require('core.plugin_config.mason')
require('core.plugin_config.outline')
-- require('core.plugin_config.lspsaga')
require('core.plugin_config.treesitter')
require('core.plugin_config.nvim-cmp')
require('core.plugin_config.hlargs')
require('core.plugin_config.telescope')
require('core.plugin_config.nvim-notify')
require('core.plugin_config.harpoon')
require('core.plugin_config.trouble')
require('core.plugin_config.tabnine')
require('core.plugin_config.luasnip')
require('core.plugin_config.nvim-dap')
require('core.plugin_config.oil')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.lualine')
require('core.plugin_config.gitsigns')
require('core.plugin_config.nvim-autopairs')
require('core.plugin_config.nvim-surround')
require('core.plugin_config.indent-blankline')
-- require('core.plugin_config.alpha-nvim')
require('core.plugin_config.tmux')
require('core.plugin_config.noice')

require('core.plugin_config.customs')

